# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ .Values.service.name }}
#   namespace: {{ .Values.namespace.name }}
# spec:
#   selector:
#     app: {{ .Values.app.name }}
#   ports:
#   - name: service
#     port: 8181
#     targetPort: 8181
#   - name: metrics
#     port: 8182
#     targetPort: 8182

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
  {{- range .Values.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
  {{- end }}